# Generated by Django 6.0.3 on 2026-03-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('clothes', 'Clothes'), ('furniture', 'Furniture'), ('electronics', 'Electronics'), ('others', 'Others')], max_length=20),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('claimed', 'Claimed'), ('expired', 'Expired')], default='available', max_length=20),
        ),
    ]
