# Generated by Django 6.0.4 on 2026-04-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
