# Generated by Django 6.0.3 on 2026-03-31 17:05

import archive.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', archive.users.models.CustomUserManager()),
            ],
        ),
    ]
